### ISSUE TITLE
`swift-sh` is not installed from bottle even in a ABI-stable environment like macOS 10.15.1

### ISSUE THREAD

**Issue by pcr910303** [mxcl/homebrew-made#7]
I was trying to install `swift-sh` from `mxcl/made/swift-sh`, and the shell output results made me curious :-) It was saying that `swift-sh` cannot be installed from bottle due to ABI instabilities, but I was using macOS 10.15.1 with Swift 5.2 so that made me wonder.

```shellsession
$ brew install mxcl/made/swift-sh
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 328e1f698 to d014d5a98.
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Tapping mxcl/made
Cloning into '/usr/local/Homebrew/Library/Taps/mxcl/homebrew-made'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
Tapped 1 formula (29 files, 27.4KB).
==> Installing swift-sh from mxcl/made
Warning: Building mxcl/made/swift-sh from source:
  The bottle requires a Swift ABI stable version of macOS
==> Downloading https://github.com/mxcl/swift-sh/archive/1.15.0.tar.gz
==> Downloading from https://codeload.github.com/mxcl/swift-sh/tar.gz/1.15.0
##O#- #                                                                       
==> swift build --configuration release --disable-sandbox
🍺  /usr/local/Cellar/swift-sh/1.15.0: 6 files, 3.6MB, built in 1 minute 52 seconds
```

I'm not really an expert in [Homebrew's DSL](https://rubydoc.brew.sh/Formula.html#pour_bottle%3F-class_method) - and you are :-), but it looks like the condition for checking whether to use bottles is reversed: it should return true (I think?) on ABI-stable environments [but it's returning false](https://github.com/mxcl/homebrew-made/blob/master/swift-sh.rb#L38).

**Comment by mxcl** [comment]
True, the Mojave bottle should be fine for Catolina. I'll take a peek.

**Comment by mxcl** [comment]
Yeah that is true, though I think we may need also to make the bottle DSL know that the Mojave bottle can be used on any MacOS above Mojave. Which is syntax I'm not familiar with, will figure it out.

Travis does not provide a Catolina image, so we’ll be building on Mojave for a while. This is somewhat related, since we could build one for each, which is safer (without the right flags, which `swift-build` doesn’t exactly support, it's possible to build a not-backwards deployable bottle), but ideally we'd build with latest Swift (for optimizations) and backwards deploy always.

**Comment by mxcl** [comment]
Unexpectedly, simply inverting the logic was sufficient. I believe it is safe, so will push this.

**Comment by mxcl** [comment]
Closed by #95b2dcd, many thanks for noticing this.

**Comment by pcr910303** [comment]
Great! Thanks for looking into this.

BTW: Canopy isn't on both the Mac App Store & App Store, is this expected? I send you an email, but just figured out asking through here might be faster.

**Comment by mxcl** [comment]
Yeah, I am aware of it. I had the opportunity for a good startup position and took it, which leaves no time to fix this situation. Partly also, the GitHub mobile apps have Sherlocked Canopy, so I’m not really motivated to fix it. Sorry :(

**Comment by pcr910303** [comment]
@mxcl Ah, okay. Thanks for responding! I didn't know about the mobile apps, so I should search about that. 👍
