### ISSUE TITLE
swift-sh bottle seems out-of-date

### ISSUE THREAD

**Issue by Frizlab** [mxcl/homebrew-made#9]
```
brew install mxcl/made/swift-sh
./my_swift_sh_script
  # -> Failure that should have been fixed with 1.18.0

brew reinstall --build-from-source mxcl/made/swift-sh
./my_swift_sh_script
  # -> Success
```

**Comment by mxcl** [comment]
Weird, the bottle was built and the formula updated:

https://github.com/mxcl/homebrew-made/commit/8f8a5df0114fe414f4bd03e65b0aa10dffd1fc78

**Comment by mxcl** [comment]
It is unfortunate that swift-sh has no version command, though this is due to the version not being surfaced automatically to our code (though I don’t see how that would be possible, needs CI to verify a static string in the code that we must update probs).

Anyway, is it possible that in fact the bottle is correct, but there is another bug causing the script to fail?

Eg. https://github.com/mxcl/swift-sh/issues/111#issuecomment-637846188

**Comment by Frizlab** [comment]
Honestly, no, I did run the same script w/ both versions of swift-sh.

To have more certainty, I did a `strings` of the build from the bottle, and the build using `--build-from-source`, and the built from source has this additional string in it:
```
.product(name: "
```
which further confort me into thinking the bottle is not up-to-date (how, I don’t know though).


Logs of what I did:
```
brew rm -f mxcl/made/swift-sh
brew install mxcl/made/swift-sh; # Install from bottle
strings /…/swift-sh >bottle.txt
brew rm -f swift-sh
brew install --build-from-source mxcl/made/swift-sh
strings /Users/frizlab/usr/homebrew/bin/swift-sh >built.txt
diff built.txt bottle.txt
```

<details>
  <summary>diff</summary>
diff built.txt bottle.txt

6c6
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/Sources/Command/editor().swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/Sources/Command/editor().swift
37,38c37,38
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/MD5.swift
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/BlockDecryptor.swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/MD5.swift
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/BlockDecryptor.swift
44c44
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/BlockEncryptor.swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/BlockEncryptor.swift
55c55
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/BlockMode/CCM.swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/BlockMode/CCM.swift
112c112
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/StreamDecryptor.swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/StreamDecryptor.swift
114c114
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/StreamEncryptor.swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/.build/checkouts/CryptoSwift/Sources/CryptoSwift/StreamEncryptor.swift
121c121
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/.build/checkouts/Path.swift/Sources/Path+CommonDirectories.swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/.build/checkouts/Path.swift/Sources/Path+CommonDirectories.swift
137d136
< .product(name: "
162,163c161
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/Sources/Script/parse().swift
< could not open: 
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/Sources/Script/parse().swift
171a170
> could not open: 
173a173
> stdout stderr 
181c181
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/Sources/Utility/exec().swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/Sources/Utility/exec().swift
187c187
< /private/tmp/swift-sh-20200603-3470-1vdswbm/swift-sh-1.18.0/.build/checkouts/Version/Sources/Version+Comparable.swift
---
> /private/tmp/swift-sh-20200601-3107-1f2ohk7/swift-sh-1.18.0/.build/checkouts/Version/Sources/Version+Comparable.swift
241,245c241,246
< swift_getObjCClassMetadata
< ySSG4argst
< _Sb5forcet
< ySSG
< yypG
---
> s11CommandLineO
> _s10ArraySliceVySSG4argst
> 4PathAAV_Sb5forcet
> 4PathAAV
> 4PathAAVSg
> 7Command10EjectErrorO
247d247
< ySay
249,252c249,255
< SaySay
< GGSg
< G4sBox_AB7invSBoxtSg
< ySiG
---
> 11CryptoSwift11SecureBytesC
> 11CryptoSwift9BlockMode_p
> 11CryptoSwift7PaddingO
> SaySays6UInt32VGGSg
> Says6UInt32VG4sBox_AC7invSBoxtSg
> Says6UInt32VGSg
> 11CryptoSwift3AESC7VariantO
254d256
< ySay
257a260
> 11CryptoSwift22BatchedCollectionIndexV
258a262
> 11CryptoSwift3BitO
259a264,265
> 11CryptoSwift16CipherModeWorker_p
> Says5UInt8VG
260a267
> 11CryptoSwift15BlockModeOptionV
264c271,278
< yAAGc
---
> 11CryptoSwift13CBCModeWorkerV
> Says5UInt8VGSgs10ArraySliceVyABGc
> s10ArraySliceVys5UInt8VG
> s10ArraySliceVys5UInt8VGSg
> Says5UInt8VGSg
> s5UInt8V
> 11CryptoSwift13CCMModeWorkerC5ErrorO
> 11CryptoSwift13CCMModeWorkerC
265a280,283
> 11CryptoSwift13CFBModeWorkerV
> 11CryptoSwift13CTRModeWorkerV
> s6UInt64V
> 11CryptoSwift13CTRModeWorkerV10CTRCounterC
272,276c290,300
< SgXw
< ySay
< GcSg
< _pSg
< SaySay
---
> 11CryptoSwift13ECBModeWorkerV
> 11CryptoSwift3GCMCSgXw
> ySays5UInt8VGcSg
> 11CryptoSwift7UInt128V
> 11CryptoSwift13OFBModeWorkerV
> 11CryptoSwift14PCBCModeWorkerV
> 11CryptoSwift16CipherModeWorker_pSg
> Says6UInt32VG
> SaySays6UInt32VGG
> 11CryptoSwift6CBCMACC
> 11CryptoSwift8ChaCha20C0cC9DecryptorV
280c304,305
< SgIegd_
---
> 11CryptoSwift19RandomBytesSequenceV
> s5UInt8VSgIegd_
282a308,309
> 11CryptoSwift4HMACC7VariantO
> 11CryptoSwift4HMACC
283a311,317
> s6UInt32V
> s15ContiguousArrayVys6UInt32VG
> Says6UInt64VG
> 11CryptoSwift4SHA2C7VariantO
> 11CryptoSwift6ScryptC5ErrorO
> s16IndexingIteratorVy11CryptoSwift11SecureBytesCG
> SIy11CryptoSwift11SecureBytesCG
286c320
< 1a_AA1bt
---
> s6UInt64V1a_AB1bt
291a326,328
> SS_s6MirrorV12DisplayStyleOSgt
> s6MirrorV12DisplayStyleOSg
> So18NSFileAttributeKeya
294,295c331,332
< _yptG
< _ypt
---
> Say4PathAAV9EntryTypeOG
> 4PathAAV9EntryTypeO
296a334
> 4PathAAV6FinderC
298a337
> Shy4PathAAV9EntryTypeOGSg
300d338
< ySSG
303d340
< ySSG
305c342
< ySsG
---
> SS5IndexV
306a344,346
> 6Script19ImportSpecificationV14DependencyNameO1EO
> 6Script19ImportSpecificationV14DependencyNameO
> 10Foundation3URLV
308c348,351
< 4from_t
---
> 6Script19ImportSpecificationV10ConstraintO
> 7VersionAAV4from_t
> 7VersionAAV
> Say6Script19ImportSpecificationVG
311d353
< Sf_Sit
313a356,358
> 6Script1EO
> s15EmptyCollectionVys5UInt8VG
> 10Foundation4DataV
315c360
< GIgy_
---
> SpySo28_ConditionalAllocationBufferaGIgy_
317,318c362,363
< ySSGG
< ySSG
---
> s11AnyIteratorVySSG
> SS10FoundationE8EncodingV
319a365,366
> So28_ConditionalAllocationBuffera
> 12StreamReaderAAC
321,322c368
< z_Xx
< 6stdout_AA6stderrt
---
> 10Foundation4DataVz_Xx
324a371
> s5Int32V
326,335c373,377
< SS10executable_
< 5errnot
< SaySpy
< GSgG
< ySpy
< GSgG
< SgIegxr_
< SgIegir_
< SiSg
< ySiSgG
---
> SS10executable_s5Int32V5errnot
> SaySpys4Int8VGSgG
> SS7VersionAAVSgIegxr_
> SS7VersionAAVSgIegir_
> SS7VersionAAVSgIegnr_
410c452
< expand 32-byte kq
---
> expand 32-byte k1
456,457d497
< RandomBytesSequence
< CryptoSwift
510d549
< _ConditionalAllocationBuffer
886d924
< initWithPattern:options:error:
888a927
> initWithPattern:options:error:
</details>

**Comment by captain-charisma** [comment]
what is the solution? @mxcl ?

**Comment by mxcl** [comment]
I installed with the bottle and it's definitely 2.0.1.
